api: LARSpigotPluginAPI
name: LARSpigotPlugin
main: lar.spigot.plugin.Main
version: ${project.version}
api-version: '1.20'
authors: [Alberto Rutigliano, Luca Acquafredda]
website: https://github.com/AlbertoRutigliano/MinecraftPluginDev
commands: 
   PlayerPos:
      description: Mostra le coordinate dei giocatori
      usage: |
        /playerpos - Mostra le coordinate di tutti i giocatori online
        /playerpos [playerName] - Mostra le coordinate del giocatore selezionato
      permission: perm.general
   Coords:
      description: Mostra le coordinate salvate sul server
      usage:  |
        /coords - Mostra tutte le coordinate salvate sul server
        /coords add <name> - Salva nuove coordinate "name" con posizione del giocatore
        /coords remove <name> - Rimuovi coordinate "name" dal server
        /coords get <name> - Mostra coordinate "name"
      permission: perm.general
   Joke:
      description: Fai uno scherzo a un tuo amico
      usage:  |
        /joke - Fai uno scherzo a tutti i giocatori online
        /joke <creeper, creeper_hurt, enderman, witch, arrow> [playerName]
      permission: perm.general
   Track:
      description: Segui le coordinate (navigatore)
      usage:  |
        /track player <playerName> - Segui il giocatore <playerName>
        /track location <locationName> - Segui delle coordinate salvate sul server
        /track new <X> <Z> - Segui le coordinate X, Z
        /track stop - Ferma il navigatore
      permission: perm.general
   Thanks:
      aliases: [grazie, grz, ty]
      description: Ringrazia un giocatore
      usage:  |
        /thanks
        /grazie
        /grz
        /ty
      permission: perm.general
permissions:
   perm.general:
      default: true
   perm.op:
      default: op
