api: MySpigotPluginAPI
name: MySpigotPlugin
main: plugin.spigot.defaulpackage.Main
version: "6.2.2"
api-version: 1.18
author: Luca Acquafredda & Alberto Rutigliano
commands: 
   PlayerPos:
      description: Mostra le coordinate dei giocatori
      usage: "Uso: /PlayerPos [playername]"
      permission: perm.general
   Coords:
      description: Mostra le coordinate salvate del server
      usage: "Uso: /Coords"
      permission: perm.general
   Joke:
      description: Fai uno scherzo a un tuo amico
      usage: "Uso: /Joke"
      permission: perm.general
permissions:
   perm.general:
      default: true
   perm.op:
      default: op
