name: Build & Deploy JAR on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del codice
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup di Java e Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Build del progetto
      - name: Build with Maven
        run: mvn clean install -B

      # 4️⃣ Upload del .jar come artefatto (opzionale)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/*.jar

      # 5️⃣ Invio del JAR via FTP
      - name: Deploy JAR via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: target/
          include: LARSpigotPlugin-*.jar
          server-dir: /home/multicraft/multicraftServer/servers/server1/plugins/
          exclude: |
            **/*.tmp
            **/*.log
